### ISSUE TITLE
how i can do width 100%

### ISSUE THREAD

**Issue by ahmed3eraqi** [Devrama/Devrama-Slider#5]

**Comment by Devrama** [comment]
Devrama slider does not support full screen, but there is a tricky way.
Suppose your image is 1024x400.
Then, set something like this

<script type="text/javascript">
	$(document).ready(function(){
	$('#my-slide').DrSlider({
		width: 1024*4, //slide width
		height: 400*4  //slide height
		}); //Yes! that's it!
	});
</script>

1024*4 and 400*4 will cover high resolution screen, and will be auto-sized in smaller screen.

**Comment by ahmed3eraqi** [comment]
thank you bro but my slider still 1240

![image](https://cloud.githubusercontent.com/assets/9159804/5845849/0cec8f54-a1c8-11e4-8846-53ae920abfa1.png)

**Comment by Devrama** [comment]
Give it height as well, and if the slider is surrounded by other block which is 1024, the slider cannot be larger than 1024 since it cannot go over the surrounded block.

**Comment by ahmed3eraqi** [comment]
yeeeeees worked thank you bro ;)
